bot.username=
bot.token=

spring.datasource.url=jdbc:postgresql://localhost:5432/caller
spring.datasource.username=
spring.datasource.password=
spring.jpa.generate-ddl=true
spring.datasource.driver-class-callerName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

telegram.bots.allowed-updates=message,edited_message,channel_post,edited_channel_post,inline_query,chosen_inline_result,callback_query,shipping_query,pre_checkout_query,poll
